### ISSUE TITLE
[QUESTION] How well does this compare to `adevtool`?

### ISSUE THREAD

**Issue by pixincreate** [chenxiaolong/afsr#1]
As the title says, how well does this compares to `adevtool` which GrapheneOS uses?  

Again, feel free to close the issue if my question makes no sense.  

I'm just trying to understand stuffs here. I was actually working on my own setup for setting on `avbroot` and just learnt that [my-avbroot-setup](https://github.com/chenxiaolong/my-avbroot-setup/blob/master/patch.py) actually achieves almost same -- starting with fetching and verifying otas, goes on to patching as well. So `adevtool` came to my mind all of a sudden.

I'm yet to try out and experiment on this (cannot leverage my phone for now). I'm just confused.

**Comment by chenxiaolong** [comment]
`adevtool` supports extracting ext4 images via the `debugfs` command, but most of its functionality is focused on extracting specific things from a stock OS image and then integrating it into the AOSP build system. It does not have a way to build a new ext4 image from extracted files because they don't really have a need for it. 

afsr only unpacks and packs ext4 images and does nothing else. Unlike other tools, it preserves all of the file metadata (timestamps, permissions, ACLs, SELinux labels, etc.) to make it as lossless as possible.

**Comment by pixincreate** [comment]
Got it, thanks for this.

Closing.
