### ISSUE TITLE
What is this used for?

### ISSUE THREAD

**Issue by axelkar** [chenxiaolong/afsr#9]
What is the project used for? Could you give an example? Is this for extracting data from OTAs?

**Comment by chenxiaolong** [comment]
Sure, I personally use it for modifying the contents of `system.img` to add some other system Android apps I wrote. In case you're interested, this is the script where I do that: https://github.com/chenxiaolong/my-avbroot-setup. It covers the entire flow from unpacking everything to repacking and re-signing the OTA.

afsr doesn't really do anything that you couldn't already do by mounting an ext4 image on a Linux system and modifying the contents directly. The main benefit is that afsr is cross-platform and the output is reproducible. I find a lot of value in having the output always be byte-for-byte identical when given the same input + the same modifications.

**Comment by oposums** [comment]
Could you please tell me what the problem is when unpacking ext images?
This is the error
afsr-1.0.2-aarch64-linux-android31
thread 'main' panicked at src/ext.rs:1192:44:
called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: Range(RangeError(Negative { what: "nanosecond", given: 1006258668, min: -999999999, max: 999999999 })), cause: None } }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by kopaygorodsky** [comment]
Is it possible to modify system.new.dat with it for Android 6.0 ?
